---
# Boostrapping the nodes with common stuff. Like wget...

- name: Install wget
  pacman: 
    name: wget 
    state: present

- name: Install Openntpd
  pacman: 
    name: openntpd 
    state: present
  register: openntpd

- name: Restart Openntpd
  systemd: 
    state: restarted 
    name: openntpd 
    enabled: yes
    daemon_reload: yes
  when: openntpd.changed == true

