---
# This playbook contains common plays that will be run on all nodes.

- name: be sure all nodes exists in /etc/hosts
  lineinfile: 
    dest: /etc/hosts 
    regexp: '.*{{ item }}$' 
    line: "{{ hostvars[item].ansible_default_ipv4.address }} {{item}}" 
    state: present
  when: hostvars[item].ansible_default_ipv4.address is defined
  with_items: "{{ groups['all'] }}"


- name: be sure hostname is set
  hostname: 
    name: "{{ inventory_hostname }}"


- name: be sure wget is installed
  pacman: name=wget state=present

