apiVersion: v1
kind: ReplicationController
metadata:
  name: docker-registry
spec:
  replicas: 1
  selector:
    app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
      - name: registry
        image: registry:2
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 5000
          name: registry
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: docker-registry
spec:
  selector:
    app: docker-registry
  ports:
  - name: registry
    port: 5000
    protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: docker-registry
spec:
  rules:
  - host: docker.snorbu.se
    http:
      paths:
      - backend:
          serviceName: docker-registry
          servicePort: 5000

