---
# Handlers for the kubernetes master (kube-apiserver, kube-scheduler, kube-controller-manager).

- name: restart kube-apiserver
  become: yes
  systemd: 
    state: restarted 
    name: kube-apiserver
    enabled: yes
    daemon_reload: yes

- name: restart kube-scheduler
  become: yes
  systemd: 
    state: restarted 
    name: kube-scheduler
    enabled: yes
    daemon_reload: yes

- name: restart kube-controller-manager
  become: yes
  systemd: 
    state: restarted 
    name: kube-controller-manager
    enabled: yes
    daemon_reload: yes
