---
# This play will install GlusterFS

- name: Create filesystem
  filesystem:
    fstype: xfs
    dev: /dev/sdb1
    opts: "-i size=512"


- name: Create brick directory
  file:
    path: /data/brick1
    state: directory

- name: Mount device to brick
  mount:
    name: /data/brick1
    src: /dev/sdb1
    state: mounted
    fstype: xfs
    opts: defaults


- name: Install GlusterFS
  pacman:
    name: glusterfs
    state: present

- name: Install GlusterFS
  pacman:
    name: rpcbind
    state: present


- name: Start GlusterFS
  systemd:
    name: glusterd
    state: started



# Gluster volume configuration.
- name: Check if Gluster volumes already exist.
  shell: "gluster volume info"
  changed_when: false
  register: gluster_volume_info

- name: Connect to Gluster peers.
  shell: "gluster peer probe {{ item }}"
  register: gluster_peer_probe
  changed_when: "'already in peer list' not in gluster_peer_probe.stdout"
  failed_when: false
  with_items: groups.master
  when: "'Volume Name: gluster' not in gluster_volume_info.stdout"


####
# Create GlusterFS volumes
####

# Medium
- name: create gluster medium volume
  gluster_volume: 
    state: present 
    name: "{{ item }}"
    bricks: /data/brick1/kbn01-{{item}}
    replicas: 2
    quota: 1.0GB
    directory: /
    cluster: "{{ groups.master | join(',')}}"
  run_once: true
  with_items:
    - medium01
    - medium02
    - medium03
    - medium04

- name: start gluster medium volume
  gluster_volume: 
    state: started 
    name:  "{{ item }}"
  run_once: true
  with_items:
    - medium01
    - medium02
    - medium03
    - medium04

## Large
- name: create large gluster volume
  gluster_volume: 
    state: present 
    name: "{{ item }}"
    bricks: /data/brick1/kbn01-{{item}}
    replicas: 2
    quota: 5.0GB
    directory: /
    cluster: "{{ groups.master | join(',')}}"
  run_once: true
  with_items:
    - large01
    - large02

- name: start large gluster volume
  gluster_volume: 
    state: started 
    name:  "{{ item }}"
  run_once: true
  with_items:
    - large01
    - large02
