---
# This playbook will install Docker

- name: Download docker binaries
  unarchive: 
    src: "https://get.docker.com/builds/Linux/x86_64/docker-1.12.1.tgz"
    remote_src: yes
    dest: /tmp/
    creates: /usr/bin/docker


- name: Install docker binary
  become: yes
  notify: restart docker
  copy: 
    remote_src: yes
    src: /tmp/docker/docker
    dest: /usr/bin/docker
    mode: "u+x"

- name: Install docker-containerd binary
  become: yes
  notify: restart docker
  copy: 
    remote_src: yes
    src: /tmp/docker/docker-containerd
    dest: /usr/bin/docker-containerd
    mode: "u+x"

- name: Install docker-containerd-ctr binary
  become: yes
  notify: restart docker
  copy: 
    remote_src: yes
    src: /tmp/docker/docker-containerd-ctr
    dest: /usr/bin/docker-containerd-ctr
    mode: "u+x"

- name: Install docker-containerd-shim binary
  become: yes
  notify: restart docker
  copy: 
    remote_src: yes
    src: /tmp/docker/docker-containerd-shim
    dest: /usr/bin/docker-containerd-shim
    mode: "u+x"

- name: Install dockerd binary
  become: yes
  notify: restart docker
  copy: 
    remote_src: yes
    src: /tmp/docker/dockerd
    dest: /usr/bin/dockerd
    mode: "u+x"

- name: Install docker-proxy binary
  become: yes
  notify: restart docker
  copy: 
    remote_src: yes
    src: /tmp/docker/docker-proxy
    dest: /usr/bin/docker-proxy
    mode: "u+x"

- name: Install docker-runc binary
  become: yes
  notify: restart docker
  copy: 
    remote_src: yes
    src: /tmp/docker/docker-runc
    dest: /usr/bin/docker-runc
    mode: "u+x"


- name: Create Docker systemd configuration file
  become: yes
  notify: restart docker
  template:
    src: ../files/docker.service
    dest: /etc/systemd/system/docker.service
