---
# This playbook installs etcd

- hosts: etcd
  become_method: sudo
  tasks:
  - name: installing wget
    become: yes
    pacman: name=wget state=present
  - name: unzipping etcd
    unarchive: src="https://github.com/coreos/etcd/releases/download/v3.0.10/etcd-v3.0.10-linux-amd64.tar.gz" remote_src=yes dest=/tmp creates=/usr/bin/etcd
  - name: installing etcd binary
    become: yes
    copy: remote_src=yes src=/tmp/etcd-v3.0.10-linux-amd64/etcd dest=/usr/bin/etcd mode="a+x"
  - name: installing etcdctl binary
    become: yes
    copy: remote_src=yes src=/tmp/etcd-v3.0.10-linux-amd64/etcdctl dest=/usr/bin/etcdctl mode="a+x"
  - name: creating etcd config directory
    become: yes
    file: 
      path: /etc/etcd
      state: directory
  - name: creating etcd data directory
    become: yes
    file: 
      path: /var/lib/etcd
      state: directory
  - name: installing ca cert
    become: yes
    copy: src=../cert/rootCA.pem dest=/etc/etcd/
  - name: installing etcd cert
    become: yes
    copy: src=../cert/etcd.pem dest=/etc/etcd/
  - name: installing etcd cert key 
    become: yes
    copy: src=../cert/etc-key.pem dest=/etc/etcd/
  - name: installing systemd file
    become: yes
    template: src=../template/etcd/etcd.service.j2 dest=/etc/systemd/system/etcd.service
  - name: restarting systemd etcd
    become: yes
    systemd: state=restarted name=etcd daemon_reload=yes
