---
# This playbook installs the Kubernetes master (apiserver, scheduler) daemons

- hosts: kbnmaster
  become_method: sudo
  tasks:
  - name: installing wget
    become: yes
    pacman: name=wget state=present
  - name: Creating worker directory
    become: yes
    file: 
      path: /var/lib/kubernetes
      state: directory
  - name: Installing CA cert
    become: yes
    copy: 
      src: ../cert/rootCA.pem
      dest: /var/lib/kubernetes
  - name: Installing Kubernetes cert
    become: yes
    copy: 
      src: ../cert/kbnmaster.pem
      dest: /var/lib/kubernetes
  - name: Installing Kubernetes private key cert
    become: yes
    copy: 
      src: ../cert/kbnmaster-key.pem
      dest: /var/lib/kubernetes
  - name: Installing authority token
    become: yes
    copy: 
      src: ../template/kbnmaster/token.csv
      dest: /var/lib/kubernetes
  - name: Installing authorization policy
    become: yes
    copy: 
      src: ../template/kbnmaster/authorization-policy.jsonl
      dest: /var/lib/kubernetes
  - name: Installing kube-apiserver
    become: yes
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64/kube-apiserver
      dest: /usr/bin
      mode: "a+x"
  - name: Installing kube-controller-manager
    become: yes
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64/kube-controller-manager
      dest: /usr/bin
      mode: "a+x"
  - name: Installing kube-scheduler
    become: yes
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64/kube-scheduler
      dest: /usr/bin
      mode: "a+x"
  - name: Installing kubectl
    become: yes
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64/kubectl
      dest: /usr/bin
      mode: "a+x"
  - name: Installing systemd kube-apiserver config
    become: yes
    template: 
      src: ../template/kbnmaster/kube-apiserver.service.j2
      dest: /etc/systemd/system/kube-apiserver.service
  - name: Installing systemd kube-scheduler config
    become: yes
    template: 
      src: ../template/kbnmaster/kube-scheduler.service.j2
      dest: /etc/systemd/system/kube-scheduler.service
  - name: Installing systemd kube-controller-manager config
    become: yes
    template: 
      src: ../template/kbnmaster/kube-controller-manager.service.j2
      dest: /etc/systemd/system/kube-controller-manager.service
  - name: starting kube-apiserver
    become: yes
    systemd: 
      state: restarted 
      name: kube-apiserver
      daemon_reload: yes
  - name: starting kube-scheduler
    become: yes
    systemd: 
      state: restarted 
      name: kube-scheduler
      daemon_reload: yes
  - name: starting kube-controller-manager
    become: yes
    systemd: 
      state: restarted 
      name: kube-controller-manager
      daemon_reload: yes
