---
# This playbook installs the Kubernetes worker

- hosts: worker
  become_method: sudo
  tasks:

# wget
  - name: make sure wget is installed
    become: yes
    pacman: name=wget state=present

# Docker
  - name: downloading docker
    unarchive: 
      src: "https://get.docker.com/builds/Linux/x86_64/docker-1.12.1.tgz"
      remote_src: yes
      dest: /tmp/
      creates: /usr/bin/docker
  - name: installing Docker
    become: yes
    copy: 
      remote_src: yes
      src: "{{ item }}"
      dest: /usr/bin
      mode: "u+x"
    with_fileglob:
    - /tmp/docker/docker*
  - name: docker systemd file
    become: yes
    template:
      src: ../template/worker/docker.service
      dest: /etc/systemd/system/docker.service
  - name: make sure Docker is running
    become: yes
    systemd:
      name: docker
      state: restarted
      daemon_reload: yes

# CNI
  - name: make sure CNI directory exists
    become: yes
    file:
      path: /opt/cni
      state: directory
  - name: downloading CNI
    become: yes
    unarchive: 
      src: "https://storage.googleapis.com/kubernetes-release/network-plugins/cni-07a8a28637e97b22eb8dfe710eeae1344f69d16e.tar.gz"
      remote_src: yes
      dest: /opt/cni/
      creates: /opt/cni/bin/cnitools

# Creating Kubernetes directory
  - name: Creating worker directory
    become: yes
    file: 
      path: /var/lib/kubernetes
      state: directory
# Installing certs
  - name: Installing CA cert
    become: yes
    copy: 
      src: ../cert/rootCA.pem
      dest: /var/lib/kubernetes
  - name: Installing Kubernetes cert
    become: yes
    copy: 
      src: ../cert/kbnworker.pem
      dest: /var/lib/kubernetes
  - name: Installing Kubernetes private key cert
    become: yes
    copy: 
      src: ../cert/kbnworker-key.pem
      dest: /var/lib/kubernetes

# Config kubelet
  - name: make sure kubelet directory exists
    become: yes
    file:
      path: /var/lib/kubelet
      state: directory
  - name: make sure kubelet config exists
    become: yes
    copy:
      src: ../template/worker/kubeconfig
      dest: /var/lib/kubelet/kubeconfig

# Downloading and installing binaries
  - name: Installing kubelet
    become: yes
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64/kubelet
      dest: /usr/bin
      mode: "a+x"
  - name: Installing kube-proxy
    become: yes
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64/kube-proxy
      dest: /usr/bin
      mode: "a+x"
  - name: Installing kubectl
    become: yes
    get_url:
      url: https://storage.googleapis.com/kubernetes-release/release/v1.4.0/bin/linux/amd64/kubectl
      dest: /usr/bin
      mode: "a+x"

# Systemd files
  - name: Installing systemd kubelet config
    become: yes
    template: 
      src: ../template/worker/kubelet.service
      dest: /etc/systemd/system/kubelet.service
  - name: Installing systemd kube-proxy config
    become: yes
    template: 
      src: ../template/worker/kube-proxy.service
      dest: /etc/systemd/system/kube-proxy.service

# Start systemd
  - name: starting kubelet
    become: yes
    systemd: 
      state: restarted 
      name: kubelet
      daemon_reload: yes
  - name: starting kube-proxy
    become: yes
    systemd: 
      state: restarted 
      name: kube-proxy
      daemon_reload: yes
